version: "3.8"

services:
  web:
    build: ./web
    ports:
      - "80:80"
    volumes:
      - ./web/html:/usr/share/nginx/html:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
