name: Deploy to Remote Server

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    name: SSH Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: 🚀 Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
          port: 22
          script: |
            cd /root/wflw
            docker-compose down
            git pull https://github.com/thev1ndu/4COSCO11C
            docker-compose build
            docker-compose up -d
